---
- name: Deploy server
  hosts: "deploy"
  roles:
    - role: ansible_course_preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy_registry
      tags: deploy_registry
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init
    - role: leave_node
      tags: leave_node

- name: Manager
  hosts: "managers"
  roles:
    - role: ansible_course_preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join

- name: Worker
  hosts: "workers"
  roles:
    - role: ansible_course_preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join
