rmqDefaults:
  - name: AMQP_EXCHANGE
    value: xchg_integrations
  - name: AMQP_USER
    value: "{{ rmq.user}}"
  - name: AMQP_PASSWORD
    value: "{{ rmq.password }}"
  - name: AMQP_HOSTNAME
    value: rmq_swarm

registry_name: localhost:5000/

services:
  - name: registry
    version: latest
  - name: api
    version: latest
  - name: app
    version: latest
  - name: converter
    version: latest
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

non_build_services:
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

configs:
  converter:
    queue: q_imageProcessor

advertise_address: 192.168.1.31
