galaxy_info:
  author: Oleksandr Hrynkov
  description: Leave node from docker swarm cluster
  company: IT SBGS
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
