- name: Initialize cluster swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ advertise_address }}"
  register: token

- name: Save tokens
  set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    cacheable: yes
